### ISSUE TITLE
ファイルをArrayBufferの連想配列ではなくfsへの参照とカレントパスで保持したい

### ISSUE THREAD

**Issue by Narazaka** [Ikagaka/NarLoader#4]
常時メモリに乗せずアドホックに読み込みたい
ただ非同期になるので扱いにくくなるのはある

**Comment by Narazaka** [comment]
そう、NanikaDirectory/Fileは
・同期的に扱えると便利
・どうせ最後にはほぼ全部読むので事前にメモリにのせるのは無駄ではない
・読まない大容量のファイル、DLLが存在するghost/masterは今回の変更でNanikaDirを使わなくなった
というのもあり
(3つ目のは最近だが)わざとfsから後から読む設計にしなかった経緯があったんだった

**Comment by Narazaka** [comment]
シェルやバルーンに結局読まないファイルは少ないし、読んでも数メガバイトですむといった結論に昔なった気がする

**Comment by Narazaka** [comment]
アホみたいにシェルがある鎮守府の不可思議な日常でさえ12MBである

**Comment by legokichi** [comment]
「起動が遅い重い問題」はメモリ量ではなくnarダウンロード+一括解凍+直列抜き色処理だったという調査結果です
https://github.com/Ikagaka/cuttlebone/issues/17

**Comment by Narazaka** [comment]
別問題とのことだし色々かわってうやむやになった。
